### ISSUE TITLE
爱企查查询报错

### ISSUE THREAD

**Issue by M1ngGod** [0x727/ShuiZe_0x727#102]
水泽-d运行时候报错
`Traceback (most recent call last):
  File "ShuiZe.py", line 1583, in <module>
    _init()
  File "ShuiZe.py", line 1496, in _init
    run_subdomain()
  File "ShuiZe.py", line 995, in run_subdomain
    Aiqicha(companyName)
  File "ShuiZe.py", line 189, in Aiqicha
    selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName)
  File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha
    selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent)
  File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start
    if _["id"] == "basic":
TypeError: string indices must be integers
`

**Comment by M1ngGod** [comment]
很奇怪，我本机可以，vps报错如上，可能python版本需要3.9

**Comment by M1ngGod** [comment]
不知道为什么会这样子，我在kali，mac宿主机都没有这样子。vps上我centos，utubun，debian都还是出现个问题

**Comment by Hazakur3** [comment]
我也遇到了这个问题，在ubuntu vps上，版本是
`Linux hecs-291939 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

目前先try-catch了，等更新

/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py
224行处修改成以下代码

```
try:
    for _ in text_json["data"]:
        if _["id"] == "basic":
            # 佟º彜¬信彁¯
            basic = _["children"]
        if _["id"] == "certRecord":
            # 潟¥设F产彝~C
            certRecord = _["children"]
except TypeError:
	pass
```

**Comment by lkhf-ai** [comment]
> 水泽-d运行时报错 `Traceback (most recent call last): File "ShuiZe.py", line 1583, in <module> _init() File "ShuiZe.py", line 1496, in _init run_subdomain() File "ShuiZe.py", line 995, in run_subdomain Aiqicha(companyName) File "ShuiZe.py", line 189, in Aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start if _["id"] == "basic": TypeError: string indices must be integers `



> 水泽-d运行时报错 `Traceback (most recent call last): File "ShuiZe.py", line 1583, in <module> _init() File "ShuiZe.py", line 1496, in _init run_subdomain() File "ShuiZe.py", line 995, in run_subdomain Aiqicha(companyName) File "ShuiZe.py", line 189, in Aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start if _["id"] == "basic": TypeError: string indices must be integers `

抓包修改下数据包头就好了，修改/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py中def start(searchContent)的headers2。

**Comment by M1ngGod** [comment]
修改头的哪个，我改了下cookie，然后ua头，发现没必要改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月5日(周二) 上午10:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [0x727/ShuiZe_0x727] 爱企查查询报错 (Issue #102)




  
水泽-d运行时报错 Traceback (most recent call last): File "ShuiZe.py", line 1583, in <module&gt; _init() File "ShuiZe.py", line 1496, in _init run_subdomain() File "ShuiZe.py", line 995, in run_subdomain Aiqicha(companyName) File "ShuiZe.py", line 189, in Aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start if _["id"] == "basic": TypeError: string indices must be integers 
   
水泽-d运行时报错 Traceback (most recent call last): File "ShuiZe.py", line 1583, in <module&gt; _init() File "ShuiZe.py", line 1496, in _init run_subdomain() File "ShuiZe.py", line 995, in run_subdomain Aiqicha(companyName) File "ShuiZe.py", line 189, in Aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent) File "/信息收集/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start if _["id"] == "basic": TypeError: string indices must be integers 
  
抓包修改下数据包头就好了，修改/ShuiZe_0x727/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py中def start(searchContent)的headers2。

**Comment by M1ngGod** [comment]
> 
这是我随便选个网站测试。上面这条是正常，下面那条vps执行的，报错
json数据： {'status': 0, 'msg': '', 'data': [{'name': '基本信息', 'total': 90, 'id': 'basic', 'available': '1', 'sort': '1', 'children': [{'name': '爱企查图谱', 'total': '', 'available': '1', 'id': 'charts'}, {'name': '工商注册', 'total': '', 'available': '1', 'id': 'business'}, {'name': '股东信息', 'total': 18, 'available': '1', 'id': 'shareholders', 'seo': 'V00023'}, {'name': '股权穿透图', 'total': '', 'available': '1', 'id': 'stockchart'}, {'name': '主要人员', 'total': 7, 'available': '1', 'id': 'directors'}, {'name': '企业受益股东', 'total': '', 'available': '1', 'id': 'finalbenefit'}, {'name': '疑似实际控制人', 'total': '', 'available': '1', 'id': 'doubtcontroller'}, {'name': '最终受益人', 'total': 1, 'available': '1', 'id': 'benefitperson'}, {'name': '对外投资', 'total': 5, 'available': 1, 'id': 'invest'}, {'name': '控股企业', 'total': 6, 'available': '1', 'id': 'hold'}, {'name': '变更记录', 'total': 45, 'available': '1', 'id': 'change'}, {'name': '企业年报', 'total': 8, 'available': '1', 'id': 'annual'}, {'name': '分支机构', 'total': 0, 'available': 0, 'id': 'branch'}, {'name': '总公司', 'total': 0, 'available': 0, 'id': 'head-company'}]}, {'name': '重点关注', 'total': 11750, 'id': 'risk', 'available': '1', 'sort': '3', 'children': [{'name': '司法解析', 'total': 2, 'available': '1', 'id': 'judicialanalysis'}, {'name': '财产线索', 'total': 11739, 'available': '1', 'id': 'assetTrack'}, {'name': '裁判文书', 'total': 2, 'available': '1', 'id': 'lawWenshu'}, {'name': '失信被执行人', 'total': 0, 'available': 0, 'id': 'discredit'}, {'name': '经营异常', 'total': 0, 'available': 0, 'id': 'abnormal'}, {'name': '行政处罚', 'total': 0, 'available': 0, 'id': 'penalties'}, {'name': '知识产权出质', 'total': 0, 'available': 0, 'id': 'intellectual'}, {'name': '股权出质', 'total': 2, 'available': '1', 'id': 'equitypledge'}, {'name': '动产抵押', 'total': 0, 'available': 0, 'id': 'chattelmortgage'}, {'name': '清算组信息', 'total': '', 'available': 0, 'id': 'clearaccount'}, {'name': '简易注销公告', 'total': 0, 'available': 0, 'id': 'simplecancellation'}, {'name': '股权冻结', 'total': 0, 'available': 0, 'id': 'stockfreeze'}, {'name': '严重违法', 'total': 0, 'available': 0, 'id': 'illegal'}, {'name': '税务违法', 'total': 0, 'available': 0, 'id': 'taxviolation'}, {'name': '开庭公告', 'total': 1, 'available': '1', 'id': 'opennotice'}, {'name': '司法拍卖', 'total': 0, 'available': 0, 'id': 'judicialauction'}, {'name': '被执行人', 'total': 0, 'available': 0, 'id': 'executedperson'}, {'name': '法院公告', 'total': 2, 'available': '1', 'id': 'courtnoticed'}, {'name': '立案信息', 'total': 2, 'available': '1', 'id': 'filinginfo'}, {'name': '限制高消费', 'total': 0, 'available': 0, 'id': 'restrictedconsumer'}, {'name': '终本案件', 'total': 0, 'available': 0, 'id': 'terminationcase'}, {'name': '税务非正常户', 'total': 0, 'available': 0, 'id': 'untax'}, {'name': '环保处罚', 'total': '', 'available': 0, 'id': 'envpunishment'}, {'name': '工程异常', 'total': 0, 'available': 0, 'id': 'engineeringanomaly'}, {'name': '欠税公告', 'total': 0, 'available': 0, 'id': 'overduetaxs'}, {'name': '债券违约', 'total': 0, 'available': 0, 'id': 'bondbreach'}, {'name': '破产重整', 'total': 0, 'available': 0, 'id': 'bankruptcyreorganization'}, {'name': '土地抵押', 'total': 0, 'available': 0, 'id': 'landmortgage'}]}, {'name': '知识产权', 'total': 11, 'available': '1', 'id': 'certRecord', 'sort': '4', 'children': [{'name': '网站备案', 'total': 0, 'available': 0, 'id': 'webRecord'}, {'name': '商标信息', 'total': 11, 'available': '1', 'id': 'mark'}, {'name': '专利信息', 'total': 0, 'available': 0, 'id': 'patent'}, {'name': '软件著作权信息', 'total': 0, 'available': 0, 'id': 'copyright'}, {'name': '作品著作权', 'total': 0, 'available': 0, 'id': 'workright'}]}, {'name': '企业发展', 'total': 7, 'available': '1', 'id': 'companyDevelop', 'sort': '5', 'children': [{'name': '融资信息', 'total': 0, 'available': 0, 'id': 'projectFinance'}, {'name': '核心成员', 'total': 7, 'available': '1', 'id': 'projectTeams'}, {'name': '企业品牌项目', 'total': 0, 'available': 0, 'id': 'projectBasic'}, {'name': '竞品信息', 'total': 0, 'available': 0, 'id': 'projectSimilars'}, {'name': '投资机构', 'total': 0, 'available': 0, 'id': 'investorData'}, {'name': '私募基金', 'total': 0, 'available': 0, 'id': 'privatefund'}]}, {'name': '经营状况', 'total': 21, 'available': '1', 'id': 'operatingCondition', 'sort': '6', 'children': [{'name': '行政许可', 'total': 0, 'available': 0, 'id': 'license'}, {'name': '质量监督检查', 'total': 0, 'available': 0, 'id': 'quality'}, {'name': '食品抽检结果', 'total': 0, 'available': 0, 'id': 'food'}, {'name': '抽查检查', 'total': 0, 'available': 0, 'id': 'randominspection'}, {'name': '双随机抽检', 'total': 0, 'available': 0, 'id': 'doublecheckup'}, {'name': '资质证书', 'total': 0, 'available': 0, 'id': 'qualificationcert'}, {'name': '财务指标', 'total': '', 'available': 0, 'id': 'financemain'}, {'name': '利润表', 'total': '', 'available': 0, 'id': 'financeprofit'}, {'name': '资产负债表', 'total': '', 'available': 0, 'id': 'balancesheet'}, {'name': '现金流量表', 'total': '', 'available': 0, 'id': 'cashflow'}, {'name': '微博', 'total': 0, 'available': 0, 'id': 'microblog'}, {'name': '微信公众号', 'total': 0, 'available': 0, 'id': 'wechatoa'}, {'name': 'APP', 'total': 0, 'available': 0, 'id': 'appinfo'}, {'name': '公司研报', 'total': 0, 'available': 0, 'id': 'companyreport'}, {'name': '相关研报', 'total': 0, 'available': 0, 'id': 'relevantreport'}, {'name': '相关公告', 'total': 16, 'available': '1', 'id': 'relevantannouncement'}, {'name': '地块公示', 'total': 0, 'available': 0, 'id': 'plotpublicity'}, {'name': '土地转让', 'total': 0, 'available': 0, 'id': 'landtransfer'}, {'name': '购地信息', 'total': 0, 'available': 0, 'id': 'landpurchaseinformation'}, {'name': '一般纳税人', 'total': 1, 'available': '1', 'id': 'taxpayer'}, {'name': '询价评估', 'total': 0, 'available': 0, 'id': 'inquiry'}, {'name': '招投标', 'total': 4, 'available': '1', 'id': 'tenderbidding'}, {'name': '进出口信用', 'total': 0, 'available': 0, 'id': 'importexport'}, {'name': '客户', 'total': 0, 'available': 0, 'id': 'customer'}, {'name': '供应商', 'total': 0, 'available': 0, 'id': 'supplier'}, {'name': '上榜榜单', 'total': 0, 'available': 0, 'id': 'companyrank'}, {'name': '招聘信息', 'total': 0, 'available': 0, 'id': 'enterprisejob'}, {'name': '工资待遇', 'total': '', 'available': 0, 'id': 'salary'}, {'name': '债券信息', 'total': 0, 'available': 0, 'id': 'bondinfo'}, {'name': '建筑资质', 'total': 0, 'available': 0, 'id': 'buildaptitudes'}, {'name': '信用评级', 'total': 0, 'available': 0, 'id': 'creditrating'}]}, {'name': '数据解读', 'total': '', 'available': 1, 'id': 'dataAnalysis', 'sort': '7', 'children': [{'name': '企业图谱', 'total': '', 'available': '1', 'id': 'relation'}, {'name': '股权穿透图', 'total': '', 'available': '1', 'id': 'stockchart'}, {'name': '企业实力', 'total': '', 'available': '1', 'id': 'regcapital'}]}, {'name': '新闻资讯', 'total': '', 'available': '1', 'id': 'koubei', 'sort': '8', 'children': [{'name': '新闻资讯', 'total': '', 'available': '1', 'id': 'newslist'}]}]}


json数据： {'status': -14, 'msg': 'https://wappass.baidu.com/static/captcha/tuxing.html?ak=33c48884b7df83d4230e07cbcd0d07fd&backurl=https%3A%2F%2Faiqicha.baidu.com%2Fcompany_detail_73122047516578%3Fp_type%3D1&timestamp=1657006807&signature=628f48740e3b1a504409e285f6a33a7c', 'data': {'ak': '33c48884b7df83d4230e07cbcd0d07fd', 'timestamp': 1657006807, 'signature': '628f48740e3b1a504409e285f6a33a7c'}}
