### ISSUE TITLE
这个怎么解决，大佬们

### ISSUE THREAD

**Issue by FlyCode555** [0x727/ShuiZe_0x727#129]
Traceback (most recent call last):
  File "/root/Documents/ShuiZe_0x727-master/ShuiZe.py", line 1642, in <module>
    _init()
  File "/root/Documents/ShuiZe_0x727-master/ShuiZe.py", line 1555, in _init
    run_subdomain()
  File "/root/Documents/ShuiZe_0x727-master/ShuiZe.py", line 1040, in run_subdomain
    othersApiTotalSubdomains = othersApiSubdomain()
  File "/root/Documents/ShuiZe_0x727-master/ShuiZe.py", line 259, in othersApiSubdomain
    from Plugins.infoGather.subdomain.othersApiSubdomains.othersApiSubdomains import othersApiRun
  File "/root/Documents/ShuiZe_0x727-master/Plugins/infoGather/subdomain/othersApiSubdomains/othersApiSubdomains.py", line 5, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by Zjj226566** [comment]
pip install cloudscraper
