### ISSUE TITLE
师傅们看看

### ISSUE THREAD

**Issue by 2328956238** [0x727/ShuiZe_0x727#163]
Traceback (most recent call last):
  File "/root/Shuize/ShuiZe.py", line 1642, in <module>
    _init()
  File "/root/Shuize/ShuiZe.py", line 1555, in _init
    run_subdomain()
  File "/root/Shuize/ShuiZe.py", line 1095, in run_subdomain
    run_cSubnet(CIP_List, Subdomains_ips, notCDNSubdomains, param_Links)
  File "/root/Shuize/ShuiZe.py", line 1116, in run_cSubnet
    webSpace_web_host_port, webSpace_service_host_port = run_webSpace(domain, SubdomainAndNotCDNIPs, [], '')
  File "/root/Shuize/ShuiZe.py", line 576, in run_webSpace
    run_quake()
  File "/root/Shuize/ShuiZe.py", line 505, in run_quake
    quake_Results, quake_web_host_port, quake_service_host_port = quakeApi.query_domain(query_str)
  File "/root/Shuize/Plugins/infoGather/WebspaceSearchEngine/quakeApi.py", line 26, in query_domain
    return query(query_str)
  File "/root/Shuize/Plugins/infoGather/WebspaceSearchEngine/quakeApi.py", line 157, in query
    quake_Results_tmp, quake_web_host_port_tmp, quake_service_host_port_tmp = filter_data(data)
  File "/root/Shuize/Plugins/infoGather/WebspaceSearchEngine/quakeApi.py", line 54, in filter_data
    product = service['product']  # 服务

**Comment by CHINA-china** [comment]
一样的

**Comment by 66qiang** [comment]
我也是谁能回答一下咋解决

**Comment by 1757001134** [comment]
一样咋解决

**Comment by Jurangren** [comment]
![image](https://github.com/0x727/ShuiZe_0x727/assets/111159360/930d9f32-a04d-4f54-9139-692ddc17c98c)
zan'shi我是这样暂时解决的，结果能获取到
