### ISSUE TITLE
quakeapi使用报错

### ISSUE THREAD

**Issue by atk7r** [0x727/ShuiZe_0x727#174]
Traceback (most recent call last):
  File "/home/kali/ShuiZe_0x727/ShuiZe.py", line 1642, in <module>
    _init()
  File "/home/kali/ShuiZe_0x727/ShuiZe.py", line 1555, in _init
    run_subdomain()
  File "/home/kali/ShuiZe_0x727/ShuiZe.py", line 1095, in run_subdomain
    run_cSubnet(CIP_List, Subdomains_ips, notCDNSubdomains, param_Links)
  File "/home/kali/ShuiZe_0x727/ShuiZe.py", line 1116, in run_cSubnet
    webSpace_web_host_port, webSpace_service_host_port = run_webSpace(domain, SubdomainAndNotCDNIPs, [], '')
  File "/home/kali/ShuiZe_0x727/ShuiZe.py", line 576, in run_webSpace
    run_quake()
  File "/home/kali/ShuiZe_0x727/ShuiZe.py", line 505, in run_quake
    quake_Results, quake_web_host_port, quake_service_host_port = quakeApi.query_domain(query_str)
  File "/home/kali/ShuiZe_0x727/Plugins/infoGather/WebspaceSearchEngine/quakeApi.py", line 26, in query_domain
    return query(query_str)
  File "/home/kali/ShuiZe_0x727/Plugins/infoGather/WebspaceSearchEngine/quakeApi.py", line 157, in query
    quake_Results_tmp, quake_web_host_port_tmp, quake_service_host_port_tmp = filter_data(data)
  File "/home/kali/ShuiZe_0x727/Plugins/infoGather/WebspaceSearchEngine/quakeApi.py", line 54, in filter_data
    product = service['product']  # 服务
KeyError: 'product'
填写的API是正确的

**Comment by KAI-HaHa** [comment]
同样，解决了吗

**Comment by Woo101** [comment]
解决了吗

**Comment by sg552** [comment]
没有解决。 直接修改 Shuize.py ,  注释掉 对应的方法。估计是360 quake返回的字段变了。报错了。

 585     #run_quake()

![图片](https://github.com/0x727/ShuiZe_0x727/assets/234533/2dbbff53-51b3-4a95-bc07-650963a14ca7)

**Comment by iamyourfath** [comment]
把quark.py里面的 filter_data函数改成这个：
`def` filter_data(data):
    quake_Results_tmp = []
    quake_web_host_port_tmp = []       # 存放开放web服务器的ip/domain和port
    quake_service_host_port_tmp = []   # 存放非Web服务器的ip/domain和port

    for each_data in data:
        ip = each_data.get('ip', '')
        port = each_data.get('port', '')
        location = each_data.get('location', {})
        service = each_data.get('service', {})  # 修正：从 'service' 获取，不是 'product'
        components = each_data.get('components', [])

        # 提取基础信息
        province_cn = location.get('province_cn', '')
        name = service.get('name', 'unknown')  # 协议类型（如 'http'）
        http_info = service.get('http', {})
        host = http_info.get('host', '')  # 子域名
        title = http_info.get('title', 'not exist')  # 标题

        # 提取产品信息（从 components 列表）
        products = []
        for comp in components:
            product_name = comp.get('product_name_en', 'unknown')
            version = comp.get('version', 'unknown')
            products.append(f"{product_name} {version}")
        product = ', '.join(products) if products else 'unknown'  # 组合所有产品信息

        # 提取证书信息（如果存在）
        cert = ''
        if 'cert' in service:
            cert = service['cert']
            cert = re.findall("DNS:(.*?)\n", cert)

        # 构造结果
        quake_Result = [host, title, ip, host, port, product, name, province_cn, cert]
        quake_Results_tmp.append(quake_Result)

        # 分类存储（Web服务 or 非Web服务）
        if name == 'http' and host:
            quake_web_host_port_tmp.append(f"{host}:{port}")
        else:
            quake_service_host_port_tmp.append([name, ip, port])

    return quake_Results_tmp, quake_web_host_port_tmp, quake_service_host_port_tmp`
