### ISSUE TITLE
docker安装后运行python3 ShuiZe.py 报错

### ISSUE THREAD

**Issue by LK00100** [0x727/ShuiZe_0x727#177]
$ python3 ShuiZe.py 
Traceback (most recent call last):
  File "/home/kali/Downloads/ShuiZe_0x727-master/ShuiZe.py", line 11, in <module>
    import openpyxl
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/__init__.py", line 4, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/compat/__init__.py", line 5, in <module>
    from .strings import (
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/compat/strings.py", line 10, in <module>
    from .numbers import NUMERIC_TYPES
  File "/usr/local/lib/python3.11/dist-packages/openpyxl/compat/numbers.py", line 49, in <module>
    numpy.float,
    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by lzh24** [comment]
卸载原来的 numpy, 安装pip install -U numpy==1.23.5
