### ISSUE TITLE
github接口调用错误

### ISSUE THREAD

**Issue by UpcLeo** [0x727/ShuiZe_0x727#24]
[password] [line:130090] username: ${ELASTICSEARCH_USERNAME}
[password] [line:130091] password: ${ELASTICSEARCH_PASSWORD}
[password] [line:130092] ---
github address: [line:138643] https://raw.githubusercontent.com/Wang-Kai/cherish-today/7f352e89a9ec85470a5765486b057c0b6bd33f70/2019/Collect_K8S_Log.md.back
[emails] : []
[password] [line:138985] username: ${ELASTICSEARCH_USERNAME}
[password] [line:138986] password: ${ELASTICSEARCH_PASSWORD}
[password] [line:138987] ---

Traceback (most recent call last):
  File "ShuiZe.py", line 1435, in <module>
    _init()
  File "ShuiZe.py", line 1355, in _init
    run_subdomain()
  File "ShuiZe.py", line 921, in run_subdomain
    githubApiSubdomains = githubApiSubdomain()
  File "ShuiZe.py", line 243, in githubApiSubdomain
    gitSensitiveInfo = get_GitSensitiveInfo(github_txt, raw_url_emails)
  File "ShuiZe.py", line 116, in get_GitSensitiveInfo
    emails = str(raw_url_emails[raw_url])
KeyError: 'https://raw.githubusercontent.com/ucloud/ucloud-sdk-python2/90fb43198df73a78d64bbd98675dc7b302856057/ucloud/services/uhost/client.py'

**Comment by SkewwG** [comment]
嗯嗯，这是最新功能的bug，明天会修复。感谢提交

**Comment by SkewwG** [comment]
已修复
