### ISSUE TITLE
刚试用了下出错了

### ISSUE THREAD

**Issue by history3** [0x727/ShuiZe_0x727#66]
Traceback (most recent call last):
  File "ShuiZe.py", line 1567, in <module>
    _init()
  File "ShuiZe.py", line 1484, in _init
    run_subdomain()
  File "ShuiZe.py", line 983, in run_subdomain
    Aiqicha(companyName)
  File "ShuiZe.py", line 189, in Aiqicha
    selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName)
  File "/root/ts/ShuiZe/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha
    selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent)
  File "/root/ts/ShuiZe/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start
    if _["id"] == "basic":
TypeError: string indices must be integers

**Comment by lzm-a11y** [comment]
哈哈，刚装好的时候顺手扫了一个目标正常，过一会扫第二个就和你一样报错了，好像是传参的问题，-d接收根域名，但是又报错不是整数，晕，输入xxx.com报错，输入xxx就正常，但是扫不出东西。
