### ISSUE TITLE
研究好了，可以运行，完美。

### ISSUE THREAD

**Issue by lzm-a11y** [0x727/ShuiZe_0x727#69]

**Comment by history3** [comment]
师傅分享一下
我ubuntu20死活不行少包
Traceback (most recent call last):
  File "/root/ts/ShuiZe_0x727-master/ShuiZe.py", line 1567, in <module>
    _init()
  File "/root/ts/ShuiZe_0x727-master/ShuiZe.py", line 1484, in _init
    run_subdomain()
  File "/root/ts/ShuiZe_0x727-master/ShuiZe.py", line 983, in run_subdomain
    Aiqicha(companyName)
  File "/root/ts/ShuiZe_0x727-master/ShuiZe.py", line 189, in Aiqicha
    selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = run_aiqicha(companyName)
  File "/root/ts/ShuiZe_0x727-master/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 280, in run_aiqicha
    selfIcpinfo_infos, invest_infos, holds_infos, branch_infos = start(searchContent)
  File "/root/ts/ShuiZe_0x727-master/Plugins/infoGather/subdomain/Aiqicha/Aiqicha.py", line 224, in start
    if _["id"] == "basic":
TypeError: string indices must be integers

**Comment by lzm-a11y** [comment]
进入到ShuiZe_0x727文件，把ShuiZe.py删了，重新下载一个ShuiZe.py 就可以了

**Comment by history3** [comment]
我改了那个cookeis也是正常的

**Comment by history3** [comment]
> 

用你的方法不行啊 功能正常么  麻烦提供下你的的那个正常ShuiZe.py
